### ISSUE TITLE
ModuleNotFoundError: No module named 'differentiable_sorting.torch'

### ISSUE THREAD

**Issue by n8xm** [johnhw/differentiable_sorting#1]
I have `differentiable_sorting` installed (using `pip install .`), and I also have PyTorch and autoray installed. While `from differentiable_sorting import bitonic_matrices, diff_sort, diff_argsort` *does* work with no apparent issue, if I run:
```
import torch
from differentiable_sorting.torch import bitonic_matrices, diff_sort
```
Then I get the following error message:
```
ModuleNotFoundError: No module named 'differentiable_sorting.torch'
```
Am I doing something wrong here?

**Comment by johnhw** [comment]
Apologies for the delay! This is fixed on PyPI, I'd forgotten to include the critical setuptools.find_packages() line in setup.py
